name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install --no-cache-dir -r requirements.txt -r requirements-flake.txt 

      - name: Lint with flake8
        run: |
          flake8 . --count --statistics
